#!/bin/bash
tableMetaData=""
function validTable (){
if [[ -f ./$1  ]]
then
	echo "THERE IS A Table WITH THE SAME NAME "
	return 0;
fi
for i in $1 ;
do
	if [[ $i =~ [^a-zA-Z] ]]		
	then
		echo "HAVE UNVALID CHARACTER >> IT MUST BE ALPHABETICS"
		return 0;
	fi
done
return 1;
} 
function validNumber(){
echo "Enter The Number Of Columns"
 while true
      do
          
            read col
            validNum=1;
            for i in $col;
            do
                  if [[ $i =~ [^0-9] ]]
                  then
                        validNum=0
                        echo "Please Enter a Number"
                  fi
            done
            if [ $validNum -eq 1 ]
            then
                  creaTableMetaData
                  insertTableMetaData
                  echo "table created successfully"
                  break
            fi
      done
}
function insertTableMetaData(){
      echo " insertTableMetaData $tableMetaData "
      echo "$col : ">>"$tableMetaData"
      isPrimary='n'
      primaryFeild
      i=0;
      while [ $i -lt $col ]
      do
            if [ $isPrimary == "n" ]
            then
                  echo "Enter y/n Is Primary "
                  read isPrimary
                  let primaryFeild=$i
            fi
            echo "Enter The Field Name"
            read fname
            echo "Enter The Field Type"
            read nullable
            echo "Enter y/n Dose it The Accept Null "
            read ftype
            if ( [ $isPrimary == "y" ] &&  [ $primaryFeild -eq $i ] )
            then
                  echo "y:$fname:$ftype \ ">>"$tableMetaData"
            else
                   echo "n:$fname:$ftype \ ">>"$tableMetaData"
            fi
            let i=$i+1;
      done

}
function creaTableMetaData(){

      tableMetaData="${table}@"
      touch ./"$tableMetaData"
}
function CreateTable(){

while true
do
      echo "Enter Table name "
      read table
      validTable $table
      if [ $? -eq 1 ]
      then
            touch ./$table
            validNumber 
            break;
      fi
   

done
}


function ListTables(){
echo "Your Tables are:"
ls 
}


function DropTable(){
echo "Enter Table name "
read table
if [[ -f ./$table ]]; then
    rm $table
    echo " Table $table Removed"
else 
    echo "invalid Table"
fi
}


function Delete_from_Table()
{
echo "TODO Delete_from_Table"
}
function Update_Table()
{
echo "TODO Delete_from_Table"
}
function Insert_into_Table()
{


      echo "Data Inserted Successfully"
}

cd ./DBMS/$name
echo "Connectd to $name Successfully"
echo "Enter Your Choice Please:"
options=("Create Table" "List Tables" "Drop Table" "Insert into Table" "Select from Table" "Delete from Table" "Update Table" "Exit")
select opt in "${options[@]}"
do
    case $opt in
            "Create Table")
                  CreateTable
                  ;;
            "List Tables")
                  ListTables
                  ;;
            "Drop Table")
                  DropTable
                  ;;
            "Insert into Table")
                  Insert_into_Table
                  ;;
            "Select from Table")
                  Select_from_Table
                  ;;
            "Delete from Table")
                  Delete_from_Table
                  ;;
            "Update Table")
                  Update_Table
                  ;;
            "Exit")
                  exit 
                  ;;
    esac
done